version: "3.1"
services:
    php:
      build:
        context: ./
        dockerfile: php.Dockerfile
      container_name: php-73
      volumes:
        - ./:/var/www/html

    webserver:
      image: nginx:1.17.10
      container_name: nginx-webserver
      links:
        - php:fpm
      environment:
        - FPM_HOST=fpm
        - FPM_PORT=9000
      volumes:
        - ./:/var/www/html
        - ./docker/nginx_conf:/etc/nginx/conf.d/
      ports:
       - "8080:80"

    db:
        platform: linux/x86_64
        image: mysql:5.7
        container_name: mysql-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: vunguyenkhanh
            MYSQL_USER: vunguyenkhanh
            MYSQL_PASSWORD: vunguyenkhanh
        ports:
            - 3306:3306